package com.mtp.attendance.services;

import jakarta.servlet.http.HttpServletRequest;
import org.springframework.stereotype.Service;
import java.util.List;

@Service
public class AntiSpoofingService {

    /**
     * Extracts the true client IP address, bypassing proxies and load balancers if necessary.
     */
    public String extractClientIp(HttpServletRequest request) {
        String xfHeader = request.getHeader("X-Forwarded-For");
        if (xfHeader == null || xfHeader.isEmpty() || "unknown".equalsIgnoreCase(xfHeader)) {
            return request.getRemoteAddr();
        }
        return xfHeader.split(",")[0].trim();
    }

    /**
     * Verifies if the request originated from an allowed company IP address.
     */
    public boolean isIpAllowed(String clientIp, List<String> allowedIps) {
        if (allowedIps == null || allowedIps.isEmpty()) {
            return false; 
        }
        return allowedIps.contains(clientIp);
    }

    /**
     * Analyzes GPS metadata for suspicious "too perfect" values commonly generated by Fake GPS apps.
     */
    public boolean isSuspiciousGpsMetadata(Double accuracyMeters, Double altitude) {
        // Many spoofing tools hardcode accuracy to exactly 1.0 or 0.0
        if (accuracyMeters != null && (accuracyMeters <= 1.0)) {
            return true;
        }
        
        // Some spoofers hardcode altitude to exactly 0.0
        if (altitude != null && altitude == 0.0) {
            return true;
        }
        
        return false;
    }
}
