// <auto-generated />
namespace MtpApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AlterModalMonitoring2020Nov07 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterModalMonitoring2020Nov07));
        
        string IMigrationMetadata.Id
        {
            get { return "202012070806186_AlterModalMonitoring2020Nov07"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
