// <auto-generated />
namespace MtpApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AlterModalBusinessSetUpCategory20200804two : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterModalBusinessSetUpCategory20200804two));
        
        string IMigrationMetadata.Id
        {
            get { return "202008240725465_AlterModalBusinessSetUpCategory20200804two"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
