// <auto-generated />
namespace MtpApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AlterModalClientAddClientCodeandRegisterDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterModalClientAddClientCodeandRegisterDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202004150528282_AlterModalClientAddClientCodeandRegisterDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
