// <auto-generated />
namespace MtpApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddmorefieldtoClientModal2020Aug14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddmorefieldtoClientModal2020Aug14));
        
        string IMigrationMetadata.Id
        {
            get { return "202008140358311_AddmorefieldtoClientModal2020Aug14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
