package com.mtp.api.security;

import org.springframework.security.crypto.bcrypt.BCrypt;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import java.nio.ByteBuffer;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.Base64;

@Component
public class AspNetIdentityPasswordEncoder implements PasswordEncoder {

    @Override
    public String encode(CharSequence rawPassword) {
        // We still use BCrypt for new passwords generated by this app
        return BCrypt.hashpw(rawPassword.toString(), BCrypt.gensalt());
    }

    @Override
    public boolean matches(CharSequence rawPassword, String encodedPassword) {
        if (encodedPassword == null || encodedPassword.isEmpty()) {
            return false;
        }

        // Check if it's a BCrypt hash (starts with $2a$, $2b$, etc.)
        if (encodedPassword.startsWith("$2a$") || encodedPassword.startsWith("$2b$") || encodedPassword.startsWith("$2y$")) {
            return BCrypt.checkpw(rawPassword.toString(), encodedPassword);
        }

        // Try to decode as ASP.NET Identity V3 hash
        try {
            byte[] decodedHash = Base64.getDecoder().decode(encodedPassword);
            
            // ASP.NET Identity V3 format marker is 0x01
            if (decodedHash.length > 0 && decodedHash[0] == 0x01) {
                boolean match = verifyV3Hash(rawPassword.toString(), decodedHash);
                System.out.println("V3 Hash Match Result: " + match);
                return match;
            }
            
            // ASP.NET Identity V2 format marker is 0x00
            if (decodedHash.length > 0 && decodedHash[0] == 0x00) {
                boolean match = verifyV2Hash(rawPassword.toString(), decodedHash);
                System.out.println("V2 Hash Match Result: " + match);
                return match;
            }
        } catch (Exception e) {
            System.out.println("Error decoding hash: " + e.getMessage());
        }

        return false;
    }

    private boolean verifyV3Hash(String password, byte[] decodedHash) throws NoSuchAlgorithmException, InvalidKeySpecException {
        // Read the parameters from the decoded hash
        ByteBuffer buffer = ByteBuffer.wrap(decodedHash);
        buffer.get(); // skip format marker (0x01)
        
        int prf = buffer.getInt();
        int iterCount = buffer.getInt();
        int saltLength = buffer.getInt();
        System.out.println("V3 Hash Details - PRF: " + prf + ", Iters: " + iterCount + ", SaltLen: " + saltLength);
        
        byte[] salt = new byte[saltLength];
        buffer.get(salt);
        
        int subkeyLength = decodedHash.length - 13 - saltLength;
        byte[] storedSubkey = new byte[subkeyLength];
        buffer.get(storedSubkey);
        
        // ASP.NET V3 PRF determines the algorithm
        String algorithm;
        switch (prf) {
            case 0: algorithm = "PBKDF2WithHmacSHA1"; break;
            case 1: algorithm = "PBKDF2WithHmacSHA256"; break;
            case 2: algorithm = "PBKDF2WithHmacSHA512"; break;
            default: algorithm = "PBKDF2WithHmacSHA256"; break;
        }
        
        PBEKeySpec spec = new PBEKeySpec(password.toCharArray(), salt, iterCount, subkeyLength * 8);
        SecretKeyFactory factory = SecretKeyFactory.getInstance(algorithm);
        byte[] testSubkey = factory.generateSecret(spec).getEncoded();
        
        return MessageDigest.isEqual(storedSubkey, testSubkey);
    }

    private boolean verifyV2Hash(String password, byte[] decodedHash) throws NoSuchAlgorithmException, InvalidKeySpecException {
        // V2 format: [0x00, salt(16 bytes), subkey(32 bytes)]
        // Uses PBKDF2 with HMAC-SHA1, 1000 iterations
        if (decodedHash.length != 49) return false;
        
        byte[] salt = new byte[16];
        System.arraycopy(decodedHash, 1, salt, 0, 16);
        
        byte[] storedSubkey = new byte[32];
        System.arraycopy(decodedHash, 17, storedSubkey, 0, 32);
        
        PBEKeySpec spec = new PBEKeySpec(password.toCharArray(), salt, 1000, 256);
        SecretKeyFactory factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA1");
        byte[] testSubkey = factory.generateSecret(spec).getEncoded();
        
        return MessageDigest.isEqual(storedSubkey, testSubkey);
    }
}
