plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.mtp'
version = '0.0.1-SNAPSHOT'

ext {
	set('springCloudVersion', "2023.0.4")
	set('lombok.version', "1.18.34")
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

repositories {
	mavenLocal()
	mavenCentral()
}

dependencies {
	implementation 'net.logstash.logback:logstash-logback-encoder:7.4'
	// implementation "io.projectreactor:reactor-core:3.6.12"
	// //log -  logback
	// implementation "ch.qos.logback:logback-classic:1.4.14"
	// // refactor-debug-agent
	// implementation "io.projectreactor:reactor-tools:3.6.12" 

	// Core Spring Boot
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// Microservices (Spring Cloud)


	// Security & JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'

	// Database & Performance
	runtimeOnly 'com.microsoft.sqlserver:mssql-jdbc'
	implementation 'com.github.ben-manes.caffeine:caffeine:3.1.8'
	implementation 'com.bucket4j:bucket4j-core:8.10.1'

	// Utils & External Services
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	implementation 'com.cloudinary:cloudinary-http5:2.1.0'
	
	// MapStruct
	implementation 'org.mapstruct:mapstruct:1.5.5.Final'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
	
	// RabbitMQ / AMQP
	implementation 'org.springframework.boot:spring-boot-starter-amqp'
	
	
	// Cloud Storage
	implementation 'com.amazonaws:aws-java-sdk-s3:1.12.720'
	
	// Excel Processing & Reports
	implementation 'org.apache.poi:poi:5.2.2'
	implementation 'org.apache.poi:poi-ooxml:5.2.2'
	implementation 'org.apache.poi:poi-ooxml-full:5.2.2'
	implementation 'org.apache.commons:commons-collections4:4.4'
	implementation 'com.github.librepdf:openpdf:1.3.30'
	implementation 'com.opencsv:opencsv:5.7.1'

	// Testing
	// testImplementation 'io.projectreactor:reactor-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
