server:
  port: 8092
  max-http-request-header-size: 8388608

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: mtp-pos-service
  datasource:
    url: jdbc:sqlserver://localhost\SQLEXPRESS;databaseName=MtpAppDB2018_full;encrypt=true;trustServerCertificate=true;
    username: sa
    password: ${DB_PASSWORD:Password123!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.SQLServerDialect
        tenant_identifier_resolver: com.mtp.pos.config.tenant.TenantIdentifierResolver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
